[project]
name = "demo"
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]
hello = 'python hello.py'

[dependencies]
cowpy = "1.1.*"

[feature.py312.dependencies]
python = "3.12.*"

[feature.py313.dependencies]
python = "3.13.*"

[environments]
py312 = ["py312"]
py313 = ["py313"]
