[project]
name = "math_demo"
version = "0.1.0"
channels = ["conda-forge"]
platforms = ["linux-64", "osx-arm64", "win-64"]

[dependencies]
python = "*"
cowpy = "*"

[tasks]
start = "python math_demo.py"